### ISSUE TITLE
Add glyphs source support

### ISSUE THREAD

**Issue by chrissimpkins** [source-foundry/fontmake-mp#5]

**Comment by chrissimpkins** [comment]
@graphicore @davelab6 

I am not familiar with the glyphs source build process but from what I can gather the glyphs source file is converted to an intermediate stage of UFO source then compiled to fonts with the designspace method call in fontmake.  

Here is where the glyphs source compile call is in fontmake https://github.com/googlei18n/fontmake/blob/cf25f09b0e2c8be2f0b7d307da25b5ad57c83f5b/Lib/fontmake/font_project.py#L354 

and the UFO variant/masters compile is buried in the designspace build method so not accessible to build the UFO files in parallel without refactoring on the fontmake end:

https://github.com/googlei18n/fontmake/blob/cf25f09b0e2c8be2f0b7d307da25b5ad57c83f5b/Lib/fontmake/font_project.py#L431

Is there any benefit to attempting to parallelize this process for individual glyphs source (i.e. to build multiple typefaces at once) for projects like your own that have hundreds/thousands of fonts that are compiled.  I suspect that this is perhaps not a common task to need to build multiple typefaces simultaneously and is driven by the timing of changes in the underlying projects?

**Comment by davelab6** [comment]
I think there is benefit; indeed I am suprised fontmake doesn't already do this :)

**Comment by chrissimpkins** [comment]
@davelab6 I don't think that we will be able to get at this with the current script.  Things will need to be refactored on the fontmake side.  My understanding is that the glyphs source files are "transpiled" to master UFO directories for each variant, then those are compiled to fonts.  There isn't an approach through a public method that allows us to access this at the UFO stage during execution.  The top level public method only exposes the glyphs source file so we can't turn this into concurrent execution at the UFO --> font stage.  There is only one glyphs source file... Discussed a refactor with Cosimo and it sounds as though it is planned at some stage.
